/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{
  //    type: 'autogenerated',
  //    dirName: '.'
  //}],

  // But you can create a sidebar manually
  basicInfo: [
    'public/pripojeni',
    'public/resource-pack-problemy',
    'public/zakladni-prikazy',
    'public/server-ekonomika',
    {
      type: 'category',
      label: 'Klasické návody',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'public/navody/minecraft-screenshots'
      ]
    },
    {
      type: 'category',
      label: 'Návody na pluginy',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'public/navody/pozemky',
        'public/navody/chestshop',
        'public/navody/residence',
        'public/navody/friends-clans',
        'public/navody/truhla-smrti',
        'public/navody/vytah',
        'public/navody/creative-roleplay'
      ],
    },
    {
      type: 'category',
      label: 'Store',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'public/store/darovani',
        'public/store/gift-karta-info'
      ]
    },
    'public/mazani-obsahu'
  ],
  adminTeam: [
    'admin_team/intro',
    'admin_team/system_trestu',
    'admin_team/delka_unbanu',
    {
      type: 'category',
      label: 'Návody',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'admin_team/ban_system',
        'admin_team/coreprotect'
      ]
    },
  ]
};

module.exports = sidebars;
